### ISSUE TITLE
Go to parent directory

### ISSUE THREAD

**Issue by psamim** [facebookexperimental/atom-quick-file-browser#1]
Hi,
How should one go one level up to the parent directory?
Thanks

**Comment by yiding** [comment]
By default this is bound to '-' (which should be the same key as to activate the feature, if you are using vim-mode). You can configure this to be anything you want, of course.

I seemed to have omitted this in the documentation, let me fix that.

**Comment by yiding** [comment]
Documentation updated in 47661a184a8e2c7d161f7df5d4b40e9b9b5fd079.
