### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by gosukiwi** [facebookexperimental/atom-quick-file-browser#2]
For the last few days, I've been developing an app on Windows. It's going well, but the lack of UNIX makes my Vim config dead, so I cannot easily use Vim here.

I decided for Atom instead, because it "just works", and I've always liked it. With the `vim-mode-plus` extension I basically had everything I needed, but one thing was missing: `vim-vinegar`.

After a few days I finally make a search for an alternative, not really thinking something would pop up, but then, this extension shows up. And it's __perfect__! I didn't realize how much I missed the way I navigate files, but it does make quite a difference.

Thank you @yiding ! You have made my day :) 

Cheers from Argentina 🍻

**Comment by yiding** [comment]
Glad you find it useful!
